package com.tti.componentes;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class CitaComponent extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button CancelarButton;
	@AutoGenerated
	private Button AgendarButton;
	@AutoGenerated
	private Button EliminarButton;
	@AutoGenerated
	private TextArea DescripcionTextArea;
	@AutoGenerated
	private TextField AsuntoTextField;
	@AutoGenerated
	private ComboBox TipoComboBox;
	@AutoGenerated
	private CheckBox DiaCheckBox;
	@AutoGenerated
	private PopupDateField DateFieldHasta;
	@AutoGenerated
	private PopupDateField DateFieldDesde;
	/**
	 * 
	 */
	private static final long serialVersionUID = -1084443510397871343L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CitaComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1,
				"top:20.0px;right:73.0px;bottom:0.0px;left:30.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(false);
		
		// DateFieldDesde
		DateFieldDesde = new PopupDateField();
		DateFieldDesde.setCaption("Desde");
		DateFieldDesde.setImmediate(false);
		DateFieldDesde.setWidth("-1px");
		DateFieldDesde.setHeight("-1px");
		DateFieldDesde.setRequired(true);
		verticalLayout_1.addComponent(DateFieldDesde);
		
		// DateFieldHasta
		DateFieldHasta = new PopupDateField();
		DateFieldHasta.setCaption("Hasta");
		DateFieldHasta.setImmediate(false);
		DateFieldHasta.setWidth("-1px");
		DateFieldHasta.setHeight("-1px");
		DateFieldHasta.setRequired(true);
		verticalLayout_1.addComponent(DateFieldHasta);
		
		// DiaCheckBox
		DiaCheckBox = new CheckBox();
		DiaCheckBox.setCaption("Dia Completo");
		DiaCheckBox.setImmediate(false);
		DiaCheckBox.setDescription("Seleccione si la cita durará todo el día");
		DiaCheckBox.setWidth("-1px");
		DiaCheckBox.setHeight("-1px");
		verticalLayout_1.addComponent(DiaCheckBox);
		
		// TipoComboBox
		TipoComboBox = new ComboBox();
		TipoComboBox.setCaption("Tipo");
		TipoComboBox.setImmediate(false);
		TipoComboBox.setWidth("-1px");
		TipoComboBox.setHeight("24px");
		TipoComboBox.setRequired(true);
		verticalLayout_1.addComponent(TipoComboBox);
		
		// AsuntoTextField
		AsuntoTextField = new TextField();
		AsuntoTextField.setCaption("Asunto");
		AsuntoTextField.setImmediate(false);
		AsuntoTextField.setDescription("De que tratará la reunión");
		AsuntoTextField.setWidth("-1px");
		AsuntoTextField.setHeight("-1px");
		AsuntoTextField.setRequired(true);
		verticalLayout_1.addComponent(AsuntoTextField);
		
		// DescripcionTextArea
		DescripcionTextArea = new TextArea();
		DescripcionTextArea.setCaption("Descripción");
		DescripcionTextArea.setImmediate(false);
		DescripcionTextArea
				.setDescription("Motivo de la reunión o puntos a tratar");
		DescripcionTextArea.setWidth("-1px");
		DescripcionTextArea.setHeight("-1px");
		verticalLayout_1.addComponent(DescripcionTextArea);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_1.addComponent(horizontalLayout_1);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// EliminarButton
		EliminarButton = new Button();
		EliminarButton.setCaption("Eliminar");
		EliminarButton.setImmediate(false);
		EliminarButton.setDescription("Elimina la cita del calendario");
		EliminarButton.setWidth("-1px");
		EliminarButton.setHeight("-1px");
		horizontalLayout_1.addComponent(EliminarButton);
		
		// AgendarButton
		AgendarButton = new Button();
		AgendarButton.setCaption("Agendar");
		AgendarButton.setImmediate(true);
		AgendarButton.setWidth("-1px");
		AgendarButton.setHeight("-1px");
		horizontalLayout_1.addComponent(AgendarButton);
		
		// CancelarButton
		CancelarButton = new Button();
		CancelarButton.setCaption("Cancelar");
		CancelarButton.setImmediate(true);
		CancelarButton.setWidth("-1px");
		CancelarButton.setHeight("-1px");
		horizontalLayout_1.addComponent(CancelarButton);
		
		return horizontalLayout_1;
	}

}
