package com.tti.windows;

import java.util.Date;
import java.util.GregorianCalendar;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Window;

public class CitaWindow extends Window {

	/*- VaadinEditorProperties={"grid":"RegularGrid,31","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public boolean AGENDAR;
	public boolean ELIMINAR;
	
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button CancelarButton;
	@AutoGenerated
	private Button AgendarButton;
	@AutoGenerated
	private Button EliminarButton;
	@AutoGenerated
	private TextArea DescripcionTextArea;
	@AutoGenerated
	private TextField AsuntoTextField;
	@AutoGenerated
	private ComboBox TipoComboBox;
	@AutoGenerated
	private CheckBox DiaCheckBox;
	@AutoGenerated
	private PopupDateField DateFieldHasta;
	@AutoGenerated
	private PopupDateField DateFieldDesde;
	/**
	 * 
	 */
	
	public GregorianCalendar fechaDesde;
	public GregorianCalendar fechaHasta;
	public String asunto;
	public String descripcion;
	private boolean diaCompleto;
	private static final long serialVersionUID = -1084443510397871343L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CitaWindow() {
		buildMainLayout();
		fechaDesde = new GregorianCalendar();
		fechaHasta = new GregorianCalendar();
		DateFieldDesde.setResolution(Resolution.MINUTE);
		DateFieldHasta.setResolution(Resolution.MINUTE);
		AGENDAR = false;
		ELIMINAR = false;
		diaCompleto = false;
		initListeners();
		setContent(mainLayout);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("-1px");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(true);
		
		// DateFieldDesde
		DateFieldDesde = new PopupDateField();
		DateFieldDesde.setCaption("Desde");
		DateFieldDesde.setImmediate(false);
		DateFieldDesde.setWidth("-1px");
		DateFieldDesde.setHeight("-1px");
		DateFieldDesde.setRequired(true);
		verticalLayout_1.addComponent(DateFieldDesde);
		
		// DateFieldHasta
		DateFieldHasta = new PopupDateField();
		DateFieldHasta.setCaption("Hasta");
		DateFieldHasta.setImmediate(false);
		DateFieldHasta.setWidth("-1px");
		DateFieldHasta.setHeight("-1px");
		DateFieldHasta.setRequired(true);
		verticalLayout_1.addComponent(DateFieldHasta);
		
		// DiaCheckBox
		DiaCheckBox = new CheckBox();
		DiaCheckBox.setCaption("Dia Completo");
		DiaCheckBox.setImmediate(false);
		DiaCheckBox.setDescription("Seleccione si la cita durará todo el día");
		DiaCheckBox.setWidth("-1px");
		DiaCheckBox.setHeight("-1px");
		verticalLayout_1.addComponent(DiaCheckBox);
		
		// TipoComboBox
		TipoComboBox = new ComboBox();
		TipoComboBox.setCaption("Tipo");
		TipoComboBox.setImmediate(false);
		TipoComboBox.setWidth("-1px");
		TipoComboBox.setHeight("24px");
		TipoComboBox.setRequired(true);
		verticalLayout_1.addComponent(TipoComboBox);
		
		// AsuntoTextField
		AsuntoTextField = new TextField();
		AsuntoTextField.setCaption("Asunto");
		AsuntoTextField.setImmediate(false);
		AsuntoTextField.setDescription("De que tratará la reunión");
		AsuntoTextField.setWidth("-1px");
		AsuntoTextField.setHeight("-1px");
		AsuntoTextField.setRequired(true);
		verticalLayout_1.addComponent(AsuntoTextField);
		
		// DescripcionTextArea
		DescripcionTextArea = new TextArea();
		DescripcionTextArea.setCaption("Descripción");
		DescripcionTextArea.setImmediate(false);
		DescripcionTextArea
				.setDescription("Motivo de la reunión o puntos a tratar");
		DescripcionTextArea.setWidth("-1px");
		DescripcionTextArea.setHeight("-1px");
		verticalLayout_1.addComponent(DescripcionTextArea);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_1.addComponent(horizontalLayout_1);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// EliminarButton
		EliminarButton = new Button();
		EliminarButton.setCaption("Eliminar");
		EliminarButton.setImmediate(true);
		EliminarButton.setDescription("Elimina la cita del calendario");
		EliminarButton.setWidth("-1px");
		EliminarButton.setHeight("-1px");
		horizontalLayout_1.addComponent(EliminarButton);
		
		// AgendarButton
		AgendarButton = new Button();
		AgendarButton.setCaption("Agendar");
		AgendarButton.setImmediate(true);
		AgendarButton.setWidth("-1px");
		AgendarButton.setHeight("-1px");
		horizontalLayout_1.addComponent(AgendarButton);
		
		// CancelarButton
		CancelarButton = new Button();
		CancelarButton.setCaption("Cancelar");
		CancelarButton.setImmediate(true);
		CancelarButton.setWidth("-1px");
		CancelarButton.setHeight("-1px");
		horizontalLayout_1.addComponent(CancelarButton);
		
		return horizontalLayout_1;
	}
	/* SETTERS */
	public void setFechaDesde(Date fechaDesde){
		DateFieldDesde.setValue(fechaDesde);
		this.fechaDesde.setTime(fechaDesde);
	}
	
	public void setFechaHasta(Date fechaHasta){
		DateFieldHasta.setValue(fechaHasta);
		this.fechaHasta.setTime(fechaHasta);
	}
	
	public void setAsunto(String asunto){
		AsuntoTextField.setValue(asunto);
		this.asunto = asunto;
	}
	public void setDescripcion(String descripcion){
		DescripcionTextArea.setValue(descripcion);
		this.descripcion = descripcion;
	}
	void setAgendar(boolean set){
		AGENDAR = set;
	}
	void setEliminar(boolean set){
		ELIMINAR = set;
	}
	public void setDiaCompleto(boolean diaCompleto){
		this.diaCompleto = diaCompleto;
		DiaCheckBox.setValue(diaCompleto);
	}
	
	/* GETTERS */
	public GregorianCalendar getFechaDesde(){
		return fechaDesde;
	}
	
	public GregorianCalendar getFechaHasta(){
		return fechaHasta;
	}
	
	public String getAsunto(){
		return asunto;
	}
	public String getDescripcion(){
		return descripcion;
	}
	boolean getAgendar(){
		return AGENDAR;
	}
	boolean getEliminar(){
		return ELIMINAR;
	}
	public boolean getDiaCompleto(){
		return diaCompleto;
	}
	
	
	/* FUNCIONES EXTRA */
	
	void initListeners(){
		AgendarButton.addClickListener(new Button.ClickListener() {
			
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				AGENDAR = true;
				asunto = AsuntoTextField.getValue();
				descripcion = DescripcionTextArea.getValue();
				fechaDesde.setTime(DateFieldDesde.getValue());
				fechaHasta.setTime(DateFieldHasta.getValue());
				close();
				
			}
		});
		
		EliminarButton.addClickListener(new Button.ClickListener() {
			
			/**
			 * 
			 */
			private static final long serialVersionUID = 6069377130065760850L;

			@Override
			public void buttonClick(ClickEvent event) {
				ELIMINAR = true;
				asunto = AsuntoTextField.getValue();
				descripcion = DescripcionTextArea.getValue();
				fechaDesde.setTime(DateFieldDesde.getValue());
				fechaHasta.setTime(DateFieldHasta.getValue());
				close();
			}
		});
		
		CancelarButton.addClickListener(new Button.ClickListener() {
			
			/**
			 * 
			 */
			private static final long serialVersionUID = -5849586714313293832L;

			@Override
			public void buttonClick(ClickEvent event) {
				close();
				
			}
		});
		
		DiaCheckBox.addValueChangeListener(new ValueChangeListener() {
			
			private static final long serialVersionUID = 5705430885888138982L;

			public void valueChange(ValueChangeEvent event) {
				diaCompleto = DiaCheckBox.getValue();
				if(diaCompleto){
					DateFieldDesde.setResolution(Resolution.DAY);
					DateFieldHasta.setResolution(Resolution.DAY);
				}else{
					DateFieldDesde.setResolution(Resolution.MINUTE);
					DateFieldHasta.setResolution(Resolution.MINUTE);
				}
				
			}
		});
		
	}
	

}
